version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/run/postgresql
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pisanggorengdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://pguser:pgpassword@db:5432/pisanggorengdb?schema=public
      - SESSION_SECRET=pisang-goreng-van-java-docker-secret-key-2024
      - NEXT_PUBLIC_WA_NUMBER=6285773728748
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  uploads:
  pgdata:
