name: Terraform CI

on:
  push:
    branches: ["main"]
    paths:
      - "pisang-van-java/infra/**"
  pull_request:
    branches: ["main"]
    paths:
      - "pisang-van-java/infra/**"

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Format Check
        working-directory: pisang-van-java/infra/cloudflare
        run: terraform fmt -check

      - name: Validate Configuration
        working-directory: pisang-van-java/infra/cloudflare
        run: terraform validate
